-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2017-11-26 11:38:40.678

-- tables
-- Table: CHITIETHOADON
CREATE TABLE CHITIETHOADON (
    SOHD int  NOT NULL,
    MAHD int  NOT NULL,
    SL int  NOT NULL,
    DONGIA int  NOT NULL,
    CONSTRAINT CHITIETHOADON_pk PRIMARY KEY  (SOHD)
);

-- Table: HOADON
CREATE TABLE HOADON (
    MAKH int  NOT NULL,
    MASP int  NOT NULL,
    MAHD int  NOT NULL,
    CONSTRAINT HOADON_pk PRIMARY KEY  (MAHD)
);

-- Table: KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH int  NOT NULL,
    TENKH nvarchar(100)  NOT NULL,
    DIACHI nvarchar(500)  NOT NULL,
    SDT int  NOT NULL,
    EMAIL nvarchar(max)  NOT NULL,
    CONSTRAINT KHACHHANG_pk PRIMARY KEY  (MAKH)
);

-- Table: LOAISANPHAM
CREATE TABLE LOAISANPHAM (
    MALOAI int  NOT NULL,
    MASP int  NOT NULL,
    TENLOAI nvarchar(100)  NOT NULL,
    CONSTRAINT LOAISANPHAM_pk PRIMARY KEY  (MALOAI)
);

-- Table: SANPHAM
CREATE TABLE SANPHAM (
    MASP int  NOT NULL,
    TENSP nvarchar(100)  NOT NULL,
    SOLUONG int  NOT NULL,
    CONSTRAINT SANPHAM_pk PRIMARY KEY  (MASP)
);

-- foreign keys
-- Reference: CHITIETHOADON_HOADON (table: CHITIETHOADON)
ALTER TABLE CHITIETHOADON ADD CONSTRAINT CHITIETHOADON_HOADON
    FOREIGN KEY (MAHD)
    REFERENCES HOADON (MAHD);

-- Reference: HOADON_KHACHHANG (table: HOADON)
ALTER TABLE HOADON ADD CONSTRAINT HOADON_KHACHHANG
    FOREIGN KEY (MAKH)
    REFERENCES KHACHHANG (MAKH);

-- Reference: HOADON_SANPHAM (table: HOADON)
ALTER TABLE HOADON ADD CONSTRAINT HOADON_SANPHAM
    FOREIGN KEY (MASP)
    REFERENCES SANPHAM (MASP);

-- Reference: LOAISANPHAM_SANPHAM (table: LOAISANPHAM)
ALTER TABLE LOAISANPHAM ADD CONSTRAINT LOAISANPHAM_SANPHAM
    FOREIGN KEY (MASP)
    REFERENCES SANPHAM (MASP);

-- End of file.

